import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useCallback, useState, useEffect, useRef } from 'react'
import { useScrollDirection } from 'react-use-scroll-direction'

import localFont from '@next/font/local'
import { Fira_Code, Ubuntu_Mono} from '@next/font/google'

const AeonikRegular = localFont({
    src: '../assets/fonts/Aeonik-Regular.woff2',
})
const AeonikLight = localFont({
    src: '../assets/fonts/Aeonik-Light.woff2',
})

const ubuntu_mono = Fira_Code({ subsets: ['latin'] , weight: '400'})

export default function Home() {

    const [spanText, setSpanText] = useState('avid')
    const [page, setPage] = useState(0)
    const [translateY, setTranslateY] = useState({ translateY: 0 })
    const [background, setBackground] = useState({ backgroundPosition: `left` })
    const { isScrollingUp, scrollTargetRef } = useScrollDirection()
    const colors=  ["left", "center", "right"]

    const main = useRef(null);


    const onScroll = useCallback(event => {
        var { innerWidth: width, innerHeight: height } = window;
        setPage(Math.round(event.target.scrollTop / height))
    }, []);
        

    useEffect(() => {
        setTranslateY({ transform: `translateY( calc(${- page * 100}% - ${3 * page}rem))` })
        setBackground({ backgroundPosition: colors[page] })

    }, [page]);



    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link href="https://fonts.cdnfonts.com/css/gallient" rel="stylesheet" />
            </Head>
            <div ref={scrollTargetRef} onScroll={onScroll} className={styles.pages_scroll}>
                <div className={styles.main} style={background} >
                    <h1 className={[styles.title, AeonikLight.className].join(" ")}>
                        Cano <br />
                        <div className={styles.title__words}>
                            D<div className={styles.title_words_container}>
                                <span style={translateY} className={styles.title__word_span}>avid</span>
                                <span style={translateY} className={[styles.title__word_span, ubuntu_mono.className].join(" ")}>ev;</span>
                                <span style={translateY} className={[styles.title__word_span] + " gallient-font"} >esing</span>
                            </div>
                        </div>
                    </h1>

                    <div className={styles.pagination}>
                        <ul className={styles.pagination__ul}>
                            <li className={styles.pagination__li}>
                                <button onClick={() => setPage(0)}  className={[styles.pagination__button, page == 0 ? "pagination__button-active" : " "].join(" ")}></button>
                            </li>
                            <li className={styles.pagination__li}>
                                <button onClick={() => setPage(1)}  className={[styles.pagination__button, page == 1 ? "pagination__button-active" : " "].join(" ")}></button>
                            </li>
                            <li className={styles.pagination__li}>
                                <button onClick={() => setPage(2)}  className={[styles.pagination__button, page == 2 ? "pagination__button-active" : " "].join(" ")}></button>
                            </li>
                        </ul>
                    </div>

                </div>
                <section id="canodav" className={[styles.home_section, styles.home_section_canodav].join(" ")}></section>
                <section id="canodev" className={[styles.home_section, styles.home_section_canodev].join(" ")}></section>
                <section id="canodes" className={[styles.home_section, styles.home_section_canodes].join(" ")}></section>
            </div>
        </div >
    )
}
